language: cpp

compiler: clang

before_install:
    - echo $LANG
    - echo $LC_ALL
    - sudo apt-add-repository ppa:irie/blender -y
    - sudo apt-add-repository ppa:sat-metalab/metalab -y
    - sudo apt-add-repository ppa:andrewrk/rucksack -y
    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential git-core subversion cmake automake libtool clang libxrandr-dev libxi-dev libboost-dev libglm-dev libglew-dev libopenimageio-dev libjsoncpp-dev libgsl0-dev libzmq3-dev libsnappy-dev libgphoto2-dev libglfw3-dev

before_script:
    - git submodule update --init

branches:
    - master
    - develop

os : linux
